# Generated by Django 4.2.2 on 2023-06-21 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('askme', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='count_answers',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='count_questions',
            field=models.IntegerField(default=0),
        ),
    ]
